// Auto-generated. Do not edit!

// (in-package learning_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ReadbookResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.is_finish = null;
    }
    else {
      if (initObj.hasOwnProperty('is_finish')) {
        this.is_finish = initObj.is_finish
      }
      else {
        this.is_finish = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ReadbookResult
    // Serialize message field [is_finish]
    bufferOffset = _serializer.bool(obj.is_finish, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ReadbookResult
    let len;
    let data = new ReadbookResult(null);
    // Deserialize message field [is_finish]
    data.is_finish = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'learning_action/ReadbookResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2b856346ef49f692419615fadca72182';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    bool is_finish
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ReadbookResult(null);
    if (msg.is_finish !== undefined) {
      resolved.is_finish = msg.is_finish;
    }
    else {
      resolved.is_finish = false
    }

    return resolved;
    }
};

module.exports = ReadbookResult;
