// Auto-generated. Do not edit!

// (in-package learning_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ReadbookGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.total_pages = null;
    }
    else {
      if (initObj.hasOwnProperty('total_pages')) {
        this.total_pages = initObj.total_pages
      }
      else {
        this.total_pages = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ReadbookGoal
    // Serialize message field [total_pages]
    bufferOffset = _serializer.uint32(obj.total_pages, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ReadbookGoal
    let len;
    let data = new ReadbookGoal(null);
    // Deserialize message field [total_pages]
    data.total_pages = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'learning_action/ReadbookGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e497a0df7b7c709de3898fc0228e4f6c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    uint32 total_pages
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ReadbookGoal(null);
    if (msg.total_pages !== undefined) {
      resolved.total_pages = msg.total_pages;
    }
    else {
      resolved.total_pages = 0
    }

    return resolved;
    }
};

module.exports = ReadbookGoal;
