(cl:defpackage learning_action-msg
  (:use )
  (:export
   "<READBOOKACTION>"
   "READBOOKACTION"
   "<READBOOKACTIONFEEDBACK>"
   "READBOOKACTIONFEEDBACK"
   "<READBOOKACTIONGOAL>"
   "READBOOKACTIONGOAL"
   "<READBOOKACTIONRESULT>"
   "READBOOKACTIONRESULT"
   "<READBOOKFEEDBACK>"
   "READBOOKFEEDBACK"
   "<READBOOKGOAL>"
   "READBOOKGOAL"
   "<READBOOKRESULT>"
   "READBOOKRESULT"
  ))

