; Auto-generated. Do not edit!


(cl:in-package learning_action-msg)


;//! \htmlinclude ReadbookFeedback.msg.html

(cl:defclass <ReadbookFeedback> (roslisp-msg-protocol:ros-message)
  ((reading_page
    :reader reading_page
    :initarg :reading_page
    :type cl:integer
    :initform 0))
)

(cl:defclass ReadbookFeedback (<ReadbookFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReadbookFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReadbookFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name learning_action-msg:<ReadbookFeedback> is deprecated: use learning_action-msg:ReadbookFeedback instead.")))

(cl:ensure-generic-function 'reading_page-val :lambda-list '(m))
(cl:defmethod reading_page-val ((m <ReadbookFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader learning_action-msg:reading_page-val is deprecated.  Use learning_action-msg:reading_page instead.")
  (reading_page m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReadbookFeedback>) ostream)
  "Serializes a message object of type '<ReadbookFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'reading_page)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'reading_page)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'reading_page)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'reading_page)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReadbookFeedback>) istream)
  "Deserializes a message object of type '<ReadbookFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'reading_page)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'reading_page)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'reading_page)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'reading_page)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReadbookFeedback>)))
  "Returns string type for a message object of type '<ReadbookFeedback>"
  "learning_action/ReadbookFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReadbookFeedback)))
  "Returns string type for a message object of type 'ReadbookFeedback"
  "learning_action/ReadbookFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReadbookFeedback>)))
  "Returns md5sum for a message object of type '<ReadbookFeedback>"
  "9f5dbf4433d93835e3df512b2552dfeb")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReadbookFeedback)))
  "Returns md5sum for a message object of type 'ReadbookFeedback"
  "9f5dbf4433d93835e3df512b2552dfeb")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReadbookFeedback>)))
  "Returns full string definition for message of type '<ReadbookFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%uint32 reading_page~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReadbookFeedback)))
  "Returns full string definition for message of type 'ReadbookFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%uint32 reading_page~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReadbookFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReadbookFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ReadbookFeedback
    (cl:cons ':reading_page (reading_page msg))
))
