; Auto-generated. Do not edit!


(cl:in-package learning_action-msg)


;//! \htmlinclude ReadbookGoal.msg.html

(cl:defclass <ReadbookGoal> (roslisp-msg-protocol:ros-message)
  ((total_pages
    :reader total_pages
    :initarg :total_pages
    :type cl:integer
    :initform 0))
)

(cl:defclass ReadbookGoal (<ReadbookGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReadbookGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReadbookGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name learning_action-msg:<ReadbookGoal> is deprecated: use learning_action-msg:ReadbookGoal instead.")))

(cl:ensure-generic-function 'total_pages-val :lambda-list '(m))
(cl:defmethod total_pages-val ((m <ReadbookGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader learning_action-msg:total_pages-val is deprecated.  Use learning_action-msg:total_pages instead.")
  (total_pages m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReadbookGoal>) ostream)
  "Serializes a message object of type '<ReadbookGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_pages)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_pages)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_pages)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_pages)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReadbookGoal>) istream)
  "Deserializes a message object of type '<ReadbookGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_pages)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_pages)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_pages)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_pages)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReadbookGoal>)))
  "Returns string type for a message object of type '<ReadbookGoal>"
  "learning_action/ReadbookGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReadbookGoal)))
  "Returns string type for a message object of type 'ReadbookGoal"
  "learning_action/ReadbookGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReadbookGoal>)))
  "Returns md5sum for a message object of type '<ReadbookGoal>"
  "e497a0df7b7c709de3898fc0228e4f6c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReadbookGoal)))
  "Returns md5sum for a message object of type 'ReadbookGoal"
  "e497a0df7b7c709de3898fc0228e4f6c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReadbookGoal>)))
  "Returns full string definition for message of type '<ReadbookGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 total_pages~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReadbookGoal)))
  "Returns full string definition for message of type 'ReadbookGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 total_pages~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReadbookGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReadbookGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ReadbookGoal
    (cl:cons ':total_pages (total_pages msg))
))
