; Auto-generated. Do not edit!


(cl:in-package learning_action-msg)


;//! \htmlinclude ReadbookResult.msg.html

(cl:defclass <ReadbookResult> (roslisp-msg-protocol:ros-message)
  ((is_finish
    :reader is_finish
    :initarg :is_finish
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ReadbookResult (<ReadbookResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReadbookResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReadbookResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name learning_action-msg:<ReadbookResult> is deprecated: use learning_action-msg:ReadbookResult instead.")))

(cl:ensure-generic-function 'is_finish-val :lambda-list '(m))
(cl:defmethod is_finish-val ((m <ReadbookResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader learning_action-msg:is_finish-val is deprecated.  Use learning_action-msg:is_finish instead.")
  (is_finish m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReadbookResult>) ostream)
  "Serializes a message object of type '<ReadbookResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_finish) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReadbookResult>) istream)
  "Deserializes a message object of type '<ReadbookResult>"
    (cl:setf (cl:slot-value msg 'is_finish) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReadbookResult>)))
  "Returns string type for a message object of type '<ReadbookResult>"
  "learning_action/ReadbookResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReadbookResult)))
  "Returns string type for a message object of type 'ReadbookResult"
  "learning_action/ReadbookResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReadbookResult>)))
  "Returns md5sum for a message object of type '<ReadbookResult>"
  "2b856346ef49f692419615fadca72182")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReadbookResult)))
  "Returns md5sum for a message object of type 'ReadbookResult"
  "2b856346ef49f692419615fadca72182")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReadbookResult>)))
  "Returns full string definition for message of type '<ReadbookResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool is_finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReadbookResult)))
  "Returns full string definition for message of type 'ReadbookResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool is_finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReadbookResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReadbookResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ReadbookResult
    (cl:cons ':is_finish (is_finish msg))
))
