// Generated by gencpp from file learning_action/ReadbookGoal.msg
// DO NOT EDIT!


#ifndef LEARNING_ACTION_MESSAGE_READBOOKGOAL_H
#define LEARNING_ACTION_MESSAGE_READBOOKGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_action
{
template <class ContainerAllocator>
struct ReadbookGoal_
{
  typedef ReadbookGoal_<ContainerAllocator> Type;

  ReadbookGoal_()
    : total_pages(0)  {
    }
  ReadbookGoal_(const ContainerAllocator& _alloc)
    : total_pages(0)  {
  (void)_alloc;
    }



   typedef uint32_t _total_pages_type;
  _total_pages_type total_pages;





  typedef boost::shared_ptr< ::learning_action::ReadbookGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_action::ReadbookGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ReadbookGoal_

typedef ::learning_action::ReadbookGoal_<std::allocator<void> > ReadbookGoal;

typedef boost::shared_ptr< ::learning_action::ReadbookGoal > ReadbookGoalPtr;
typedef boost::shared_ptr< ::learning_action::ReadbookGoal const> ReadbookGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_action::ReadbookGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_action::ReadbookGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_action::ReadbookGoal_<ContainerAllocator1> & lhs, const ::learning_action::ReadbookGoal_<ContainerAllocator2> & rhs)
{
  return lhs.total_pages == rhs.total_pages;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_action::ReadbookGoal_<ContainerAllocator1> & lhs, const ::learning_action::ReadbookGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learning_action::ReadbookGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_action::ReadbookGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_action::ReadbookGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_action::ReadbookGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_action::ReadbookGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_action::ReadbookGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_action::ReadbookGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e497a0df7b7c709de3898fc0228e4f6c";
  }

  static const char* value(const ::learning_action::ReadbookGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe497a0df7b7c709dULL;
  static const uint64_t static_value2 = 0xe3898fc0228e4f6cULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_action::ReadbookGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_action/ReadbookGoal";
  }

  static const char* value(const ::learning_action::ReadbookGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_action::ReadbookGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"uint32 total_pages\n"
;
  }

  static const char* value(const ::learning_action::ReadbookGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_action::ReadbookGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_pages);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadbookGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_action::ReadbookGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_action::ReadbookGoal_<ContainerAllocator>& v)
  {
    s << indent << "total_pages: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_pages);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_ACTION_MESSAGE_READBOOKGOAL_H
